### ISSUE TITLE
Cannot redeclare po_get_ssl_url()

### ISSUE THREAD

**Issue by Mouxy** [tripflex/whmcs-pushover#1]
When trying to access the addons page, I receive this error: 

Fatal error: Cannot redeclare po_get_ssl_url() (previously declared in /home/cloud/public_html/modules/addons/pushover/functions.php:19) in /home/cloud/public_html/modules/addons/pushover/functions.php on line 29

This happens for every functions.

**Comment by tripflex** [comment]
Thanks, as mentioned in the email this method of obtaining the configuration details was a temporary method until I could get a response from WHMCS on the correct way to get the details.

I did receive a response and will push an update with the new method sometime today.

Thanks for creating the issue this helps to track changes and fixes along the way.

**Comment by Mouxy** [comment]
Thanks for the software!

**Comment by tripflex** [comment]
Looks like I was wrong about the config, didn't look at code until just now.  For some reason I included require statement in addon module file (even though no functions are used in it yet), but I just pulled in the fix for it.

Let me know if you find any other issues, thanks!
